DROP TABLE IF EXISTS dim_currency;

CREATE TABLE dim_currency (
    ID BINARY(16) PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())),
    name VARCHAR(255) NOT NULL,
    code VARCHAR(255) UNIQUE NOT NULL
);

INSERT INTO dim_currency (name, code) VALUES
('Afghan Afghani', 'AFN'),
('Albanian Lek', 'ALL'),
('Algerian Dinar', 'DZD'),
('Angolan Kwanza', 'AOA'),
('Argentine Peso', 'ARS'),
('Armenian Dram', 'AMD'),
('Aruban Florin', 'AWG'),
('Australian Dollar', 'AUD'),
('Azerbaijani Manat', 'AZN'),
('Bahamian Dollar', 'BSD'),
('Bahraini Dinar', 'BHD'),
('Bangladeshi Taka', 'BDT'),
('Barbadian Dollar', 'BBD'),
('Belarusian Ruble', 'BYN'),
('Belize Dollar', 'BZD'),
('Bermudian Dollar', 'BMD'),
('Bhutanese Ngultrum', 'BTN'),
('Bolivian Boliviano', 'BOB'),
('Bosnia-Herzegovina Convertible Mark', 'BAM'),
('Botswana Pula', 'BWP'),
('Brazilian Real', 'BRL'),
('Brunei Dollar', 'BND'),
('Bulgarian Lev', 'BGN'),
('Burundi Franc', 'BIF'),
('Cape Verdean Escudo', 'CVE'),
('Cambodian Riel', 'KHR'),
('Canadian Dollar', 'CAD'),
('Cayman Islands Dollar', 'KYD'),
('Central African CFA Franc', 'XAF'),
('Chilean Peso', 'CLP'),
('Chinese Yuan Renminbi', 'CNY'),
('Colombian Peso', 'COP'),
('Comorian Franc', 'KMF'),
('Congolese Franc', 'CDF'),
('Costa Rican Colón', 'CRC'),
('Croatian Kuna', 'HRK'),
('Cuban Convertible Peso', 'CUC'),
('Cuban Peso', 'CUP'),
('Czech Koruna', 'CZK'),
('Danish Krone', 'DKK'),
('Djiboutian Franc', 'DJF'),
('Dominican Peso', 'DOP'),
('East Caribbean Dollar', 'XCD'),
('Egyptian Pound', 'EGP'),
('Eritrean Nakfa', 'ERN'),
('Estonian Kroon', 'EEK'), -- historical
('Ethiopian Birr', 'ETB'),
('Euro', 'EUR'),
('Falkland Islands Pound', 'FKP'),
('Fijian Dollar', 'FJD'),
('Gambian Dalasi', 'GMD'),
('Georgian Lari', 'GEL'),
('Ghanaian Cedi', 'GHS'),
('Gibraltar Pound', 'GIP'),
('Guatemalan Quetzal', 'GTQ'),
('Guinean Franc', 'GNF'),
('Guyanaese Dollar', 'GYD'),
('Haitian Gourde', 'HTG'),
('Honduran Lempira', 'HNL'),
('Hong Kong Dollar', 'HKD'),
('Hungarian Forint', 'HUF'),
('Icelandic Króna', 'ISK'),
('Indian Rupee', 'INR'),
('Indonesian Rupiah', 'IDR'),
('Iranian Rial', 'IRR'),
('Iraqi Dinar', 'IQD'),
('Israeli New Shekel', 'ILS'),
('Jamaican Dollar', 'JMD'),
('Japanese Yen', 'JPY'),
('Jordanian Dinar', 'JOD'),
('Kazakhstani Tenge', 'KZT'),
('Kenyan Shilling', 'KES'),
('Kuwaiti Dinar', 'KWD'),
('Kyrgyzstani Som', 'KGS'),
('Lao Kip', 'LAK'),
('Lebanese Pound', 'LBP'),
('Lesotho Loti', 'LSL'),
('Liberian Dollar', 'LRD'),
('Libyan Dinar', 'LYD'),
('Macanese Pataca', 'MOP'),
('Macedonian Denar', 'MKD'),
('Malagasy Ariary', 'MGA'),
('Malawian Kwacha', 'MWK'),
('Malaysian Ringgit', 'MYR'),
('Maldivian Rufiyaa', 'MVR'),
('Mauritanian Ouguiya', 'MRU'),
('Mauritian Rupee', 'MUR'),
('Mexican Peso', 'MXN'),
('Moldovan Leu', 'MDL'),
('Mongolian Tögrög', 'MNT'),
('Moroccan Dirham', 'MAD'),
('Mozambican Metical', 'MZN'),
('Myanmar Kyat', 'MMK'),
('Namibian Dollar', 'NAD'),
('Nepalese Rupee', 'NPR'),
('Netherlands Antillean Guilder', 'ANG'),
('New Zealand Dollar', 'NZD'),
('Nicaraguan Córdoba', 'NIO'),
('Nigerian Naira', 'NGN'),
('North Korean Won', 'KPW'),
('Norwegian Krone', 'NOK'),
('Omani Rial', 'OMR'),
('Pakistani Rupee', 'PKR'),
('Panamanian Balboa', 'PAB'),
('Papua New Guinean Kina', 'PGK'),
('Paraguayan Guaraní', 'PYG'),
('Peruvian Sol', 'PEN'),
('Philippine Peso', 'PHP'),
('Polish Złoty', 'PLN'),
('Qatari Riyal', 'QAR'),
('Romanian Leu', 'RON'),
('Russian Ruble', 'RUB'),
('Rwandan Franc', 'RWF'),
('Saint Helena Pound', 'SHP'),
('Samoan Tala', 'WST'),
('São Tomé and Príncipe Dobra', 'STN'),
('Saudi Riyal', 'SAR'),
('Serbian Dinar', 'RSD'),
('Seychellois Rupee', 'SCR'),
('Sierra Leonean Leone', 'SLL'),
('Singapore Dollar', 'SGD'),
('Solomon Islands Dollar', 'SBD'),
('Somali Shilling', 'SOS'),
('South African Rand', 'ZAR'),
('South Korean Won', 'KRW'),
('South Sudanese Pound', 'SSP'),
('Sri Lankan Rupee', 'LKR'),
('Sudanese Pound', 'SDG'),
('Surinamese Dollar', 'SRD'),
('Swazi Lilangeni', 'SZL'),
('Swedish Krona', 'SEK'),
('Swiss Franc', 'CHF'),
('Syrian Pound', 'SYP'),
('Tajikistani Somoni', 'TJS'),
('Tanzanian Shilling', 'TZS'),
('Thai Baht', 'THB'),
('Tongan Paʻanga', 'TOP'),
('Trinidad and Tobago Dollar', 'TTD'),
('Tunisian Dinar', 'TND'),
('Turkish Lira', 'TRY'),
('Turkmenistani Manat', 'TMT'),
('Ugandan Shilling', 'UGX'),
('Ukrainian Hryvnia', 'UAH'),
('United Arab Emirates Dirham', 'AED'),
('United States Dollar', 'USD'),
('United Kingdom', 'GBP'),
('Uruguayan Peso', 'UYU'),
('Uzbekistani Som', 'UZS'),
('Vanuatu Vatu', 'VUV'),
('Venezuelan Bolívar', 'VES'),
('Vietnamese Đồng', 'VND'),
('Yemeni Rial', 'YER'),
('Zambian Kwacha', 'ZMW'),
('Zimbabwean Dollar', 'ZWL');
